/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package process;

import Data.ShareData;
import Data.giaovienData;
import Data.hocvienData;
import N10.GiaoVien;

/**
 *
 * @author An Nhien
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    public static String hocvienID;
//    giaovienData gvData = new giaovienData();
//    hocvienData hvData=new hocvienData();

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
        hocvienID = lbltendangnhap.getText();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btdethi = new javax.swing.JButton();
        btlop = new javax.swing.JButton();
        btHV = new javax.swing.JButton();
        btmon = new javax.swing.JButton();
        btcapnhat = new javax.swing.JButton();
        btGV = new javax.swing.JButton();
        btout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnkq = new javax.swing.JButton();
        lbltendangnhap = new javax.swing.JLabel();
        lblvaitro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btdethi.setBackground(new java.awt.Color(0, 153, 153));
        btdethi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btdethi.setForeground(new java.awt.Color(255, 255, 255));
        btdethi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/test-icon.png"))); // NOI18N
        btdethi.setText("ĐỀ THI");
        btdethi.setBorderPainted(false);
        btdethi.setFocusPainted(false);
        btdethi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdethiActionPerformed(evt);
            }
        });

        btlop.setBackground(new java.awt.Color(0, 153, 153));
        btlop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btlop.setForeground(new java.awt.Color(255, 255, 255));
        btlop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Science-Classroom-icon.png"))); // NOI18N
        btlop.setText("LỚP HỌC");
        btlop.setBorderPainted(false);
        btlop.setFocusPainted(false);
        btlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlopActionPerformed(evt);
            }
        });

        btHV.setBackground(new java.awt.Color(0, 153, 153));
        btHV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btHV.setForeground(new java.awt.Color(255, 255, 255));
        btHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/students.png"))); // NOI18N
        btHV.setText("HỌC VIÊN\n");
        btHV.setBorderPainted(false);
        btHV.setFocusPainted(false);
        btHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHVActionPerformed(evt);
            }
        });

        btmon.setBackground(new java.awt.Color(0, 153, 153));
        btmon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmon.setForeground(new java.awt.Color(255, 255, 255));
        btmon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/target.png"))); // NOI18N
        btmon.setText("MÔN HỌC");
        btmon.setBorderPainted(false);
        btmon.setFocusPainted(false);
        btmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmonActionPerformed(evt);
            }
        });

        btcapnhat.setBackground(new java.awt.Color(0, 153, 153));
        btcapnhat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcapnhat.setForeground(new java.awt.Color(255, 255, 255));
        btcapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/browser.png"))); // NOI18N
        btcapnhat.setText("CẬP NHẬT\n");
        btcapnhat.setBorderPainted(false);
        btcapnhat.setFocusPainted(false);
        btcapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcapnhatActionPerformed(evt);
            }
        });

        btGV.setBackground(new java.awt.Color(0, 153, 153));
        btGV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btGV.setForeground(new java.awt.Color(255, 255, 255));
        btGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/teacher (1).png"))); // NOI18N
        btGV.setText("GIÁO VIÊN\n");
        btGV.setBorderPainted(false);
        btGV.setFocusPainted(false);
        btGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGVActionPerformed(evt);
            }
        });

        btout.setBackground(new java.awt.Color(0, 153, 153));
        btout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btout.setForeground(new java.awt.Color(255, 255, 255));
        btout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        btout.setText("ĐĂNG XUẤT\n");
        btout.setBorderPainted(false);
        btout.setFocusPainted(false);
        btout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo-teky.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HOME");
        jLabel2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("CÔNG TY CP CÔNG NGHỆ & SÁNG TẠO TRẺ TEKY HOLDINGS "); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Điện thoại: 024-7109-6668");

        btnkq.setBackground(new java.awt.Color(0, 153, 153));
        btnkq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnkq.setForeground(new java.awt.Color(255, 255, 255));
        btnkq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exam.png"))); // NOI18N
        btnkq.setText("KẾT QUẢ");
        btnkq.setBorderPainted(false);
        btnkq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkqActionPerformed(evt);
            }
        });

        lbltendangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltendangnhap.setText("jLabel5");

        lblvaitro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblvaitro.setText("jLabel6");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/human (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(btout)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btlop)
                        .addGap(89, 89, 89)
                        .addComponent(btHV)
                        .addGap(96, 96, 96)
                        .addComponent(btGV)
                        .addGap(85, 85, 85)
                        .addComponent(btcapnhat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(btdethi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnkq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btmon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblvaitro, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(lbltendangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbltendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(lblvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1))
                    .addComponent(jLabel5))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btdethi)
                            .addComponent(btnkq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btmon))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btcapnhat)
                        .addComponent(btlop)
                        .addComponent(btHV)
                        .addComponent(btGV)))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(btout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        private void processLoginSuccess() {
        lbltendangnhap.setText(ShareData.NguoiDdangNhap.getTendangnhap());

        lblvaitro.setText(ShareData.NguoiDdangNhap.getVaitro());
        if (ShareData.NguoiDdangNhap.getVaitro().equals("Học viên")) {
            btcapnhat.setEnabled(false);
        }
        hocvienID = lbltendangnhap.getText();
       
    }
    private void btHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHVActionPerformed
        // TODO add your handling code here:
        JHocVien jhv = new JHocVien();
        jhv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btHVActionPerformed

    private void btcapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcapnhatActionPerformed
        // TODO add your handling code here:
        JUpdate jup = new JUpdate();
        jup.setVisible(true);
        dispose();

    }//GEN-LAST:event_btcapnhatActionPerformed

    private void btGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGVActionPerformed
        // TODO add your handling code here:
        JGiaoVien jgv = new JGiaoVien();
        jgv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btGVActionPerformed

    private void btoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoutActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_btoutActionPerformed

    private void btdethiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdethiActionPerformed
        // TODO add your handling code here:
        AllTest at = new AllTest();
        at.setVisible(true);
        dispose();
    }//GEN-LAST:event_btdethiActionPerformed

    private void btlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlopActionPerformed
        // TODO add your handling code here:
        JLopHoc jlop = new JLopHoc();
        jlop.setVisible(true);
        dispose();
    }//GEN-LAST:event_btlopActionPerformed

    private void btmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmonActionPerformed
        // TODO add your handling code here:
        JMonHoc jmon = new JMonHoc();
        jmon.setVisible(true);
        dispose();
    }//GEN-LAST:event_btmonActionPerformed

    private void btnkqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkqActionPerformed
        // TODO add your handling code here:
        KetQua kq = new KetQua();
        kq.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkqActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        processLoginSuccess();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GiaoDienChinh().setVisible(true);
                GiaoDienChinh chinh = new GiaoDienChinh();
                chinh.setLocationRelativeTo(null);
                chinh.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGV;
    private javax.swing.JButton btHV;
    private javax.swing.JButton btcapnhat;
    private javax.swing.JButton btdethi;
    private javax.swing.JButton btlop;
    private javax.swing.JButton btmon;
    private javax.swing.JButton btnkq;
    private javax.swing.JButton btout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbltendangnhap;
    private javax.swing.JLabel lblvaitro;
    // End of variables declaration//GEN-END:variables
}
